//
//  Calling out to targets
//  
exports.callout = function(target, resources) {
    switch (target) {
    case 'aws':
        aws(resources);
        break;
    case 'rackspace':
        rackspace(resources);
        break;
    }
};

function aws(resources) {
    var template, r = {};

    resources.forEach(function(resource) {
        var name = Object.keys(resource)[0];
        r[name] = resource[name];
    });

    template = {
        AWSTemplateFormatVersion: '2010-09-09',
        Description: 'Generated by CloudML',
        Resources: r
    };

    console.log(require('util').inspect(template, true, null));
}

function rackspace(resources) {}

