//
//  Calling out to targets
//  
var https = require('https');

exports.callout = function(target, resources) {
    switch (target) {
    case 'aws':
        aws(resources);
        break;
    case 'rackspace':
        rackspace(resources);
        break;
    }
};

function aws(resources) {
    var template, r = {},
    options = {
        host: 'cloudformation.us-east-1.amazonaws.com',
        //host: 'localhost',
        //port: 9001,
        method: 'POST'
    },
    req;

    resources.forEach(function(resource) {
        var name = Object.keys(resource)[0];
        r[name] = resource[name];
    });

    template = {
        AWSTemplateFormatVersion: '2010-09-09',
        Description: 'Generated by CloudML',
        Resources: r
    };

    console.log(require('util').inspect(template, false, null));

    var req = https.request(options, function(res) {
        console.log('STATUS: ' + res.statusCode);
        console.log('HEADERS: ' + JSON.stringify(res.headers));
        res.setEncoding('utf8');
        res.on('data', function(chunk) {
            console.log('BODY: ' + chunk);
        });
    });

    req.on('error', function(e) {
        console.log('problem with request: ' + e.message);
    });

}

function rackspace(resources) {
    console.log(require('util').inspect(resources, false, null));
}

